{ # noqa
    'name': 'Furniture Order Management',
    'summary': 'Управление заказами мебельной фабрики',
    'author': "Dmitriy",
    'category': 'Manufacturing',
    'version': '0.1',
    'license': 'AGPL-3',
    'depends': ['base'],
    'data': [
        'security/ir.model.access.csv',
        'data/sequence_data.xml',
        'data/sample_data.xml',
        'reports/transport_label_templates.xml',
        'reports/transport_label_report.xml',
        'views/product_views.xml',
        'views/customer_views.xml',
        'views/picker_views.xml',
        'views/order_views.xml',
        'views/product_import_wizard_views.xml',
        'views/furniture_menus.xml',
    ],
    'installable': True,
    'application': True,
}
